# Generated by Django 5.1.3 on 2025-05-02 17:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohere_app', '0002_delete_usernames'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10)),
                ('usecase', models.CharField(choices=[('chat', 'Chat'), ('qa', 'QA')], default='chat', max_length=10)),
            ],
        ),
    ]
