# Generated by Django 5.1.3 on 2025-05-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohere_app', '0003_sessiondetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompthistory',
            name='usecase',
            field=models.CharField(choices=[('chat', 'Chat'), ('qa', 'QA')], default='chat', help_text='The type of interaction: chat conversation or QA retrieval.', max_length=10),
        ),
    ]
