# Generated by Django 5.1.3 on 2025-05-06 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohere_app', '0004_prompthistory_usecase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompthistory',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='sessiondetails',
            name='session_id',
        ),
    ]
