# Generated by Django 5.1.3 on 2025-05-06 11:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohere_app', '0005_remove_prompthistory_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompthistory',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
