# Generated by Django 5.1.3 on 2025-05-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohere_app', '0006_prompthistory_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiondetails',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
