# Generated by Django 5.1.3 on 2025-05-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohere_app', '0007_alter_sessiondetails_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessiondetails',
            name='usecase',
        ),
        migrations.AddField(
            model_name='sessiondetails',
            name='usecase1',
            field=models.CharField(choices=[('chat', 'Chat')], default='chat', help_text='Primary usecase (always chat).', max_length=10),
        ),
        migrations.AddField(
            model_name='sessiondetails',
            name='usecase2',
            field=models.CharField(blank=True, choices=[('qa', 'QA')], help_text='Secondary usecase (QA) for hard-coded users.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prompthistory',
            name='usecase',
            field=models.CharField(choices=[('chat', 'chat'), ('qa', 'qa')], default='chat', help_text='The type of interaction: chat or QA.', max_length=10),
        ),
    ]
