# Generated by Django 5.1.3 on 2025-05-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohere_app', '0008_remove_sessiondetails_usecase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10)),
                ('usecase1', models.CharField(choices=[('chat', 'Chat')], default='chat', help_text='Primary usecase (always chat).', max_length=10)),
                ('usecase2', models.CharField(blank=True, choices=[('qa', 'QA')], help_text='Secondary usecase (QA) for hard-coded users.', max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SessionDetails',
        ),
    ]
