# Generated by Django 5.1.3 on 2025-05-08 04:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohere_app', '0009_userinfo_delete_sessiondetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='usecase1',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='usecase2',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='usecase',
            field=models.CharField(blank=True, choices=[('chat', 'Chat'), ('qa', 'QA')], help_text="Leave null for most users; set to 'qa' in login for your selected users.", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prompthistory',
            name='usecase',
            field=models.CharField(blank=True, choices=[('qa', 'QA')], help_text="Set to 'qa' for QA prompts; leave blank for chat.", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
