# Generated by Django 5.1.3 on 2025-05-08 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohere_app', '0010_remove_userinfo_usecase1_remove_userinfo_usecase2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='session_id',
        ),
    ]
