# Generated by Django 5.1.3 on 2025-05-15 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cohere_app', '0011_remove_userinfo_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompthistory',
            name='usecase',
        ),
    ]
