# Generated by Django 5.1.3 on 2025-05-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cohere_app', '0012_remove_prompthistory_usecase'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompthistory',
            name='usecase',
            field=models.CharField(choices=[('chat', 'chat'), ('qa', 'qa')], default='chat', help_text='The type of interaction: chat or QA.', max_length=10),
        ),
    ]
